{
 "title": "Dashboard Perbandingan Transaksi Inflow & Outflow EDC dan QRIS BRI",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Transaksi QRIS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#001852;\"><b><font size=\"5\" color=\"#fffff\">\nTransaction QRIS Realtime\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Frekuensi Selisih Inflow Outflow Transaksi QRIS Realtime (Ribu Transaksi) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Inflow",
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outflow",
     "bucketAggs": [
      { "field": "TransactionDatetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Responsecode :\"00\"",
     "timeField": "TransactionDatetime"
    }
   ]
  },
  {
   "title": "Volume Selisih Inflow Outflow Transaksi QRIS Realtime (Rp Milyar) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "alias": "Inflow",
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trx_amount_fix", "id": "1", "type": "sum" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outflow",
     "bucketAggs": [
      { "field": "TransactionDatetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data_REQUEST_transactionAmount", "id": "1", "type": "sum" }
     ],
     "query": "Responsecode :\"00\"",
     "timeField": "TransactionDatetime"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#001852;\"><b><font size=\"5\" color=\"#fffff\">\nTransaction QRIS Daily\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Frekuensi Selisih Inflow Outflow Transaksi QRIS Daily (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  SELECT \r\n    --CONVERT(VARCHAR(10),trx_date,120) trx_date\r\n    trx_date\r\n    ,convert(decimal(18,2),SUM(jumlah_transaksi)/1000) transaction_frequency\r\n  FROM [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()) < 30 \r\n  GROUP BY \r\n    trx_date\r\n    --CONVERT(VARCHAR(10),trx_date,120)\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,trx_date,105),1,2) trx_date\r\n  ,transaction_frequency metrics_value\r\nfrom a\r\norder by a.trx_date"
    },
    {
     "rawSql": "with  a as (\r\n  SELECT \r\n    --CONVERT(VARCHAR(10),TANGGAL_TRANSAKSI,120) trx_date\r\n    TANGGAL_TRANSAKSI\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_TOTAL)/1000) transaction_frequency\r\n  FROM QRIS.dbo.TRANSAKSI_MPM_OFF_US_SUMMARY_DAILY_SUCCESS_ONLY\r\n  WHERE \r\n    DATEDIFF(DAY,TANGGAL_TRANSAKSI,GETDATE()) < 30 \r\n  GROUP BY \r\n    TANGGAL_TRANSAKSI\r\n    --CONVERT(VARCHAR(10),TANGGAL_TRANSAKSI,120)\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,TANGGAL_TRANSAKSI,105),1,2) trx_date\r\n  ,transaction_frequency metrics_value\r\nfrom a\r\norder by a.TANGGAL_TRANSAKSI"
    }
   ]
  },
  {
   "title": "Volume Selisih Inflow Outflow Transaksi QRIS Daily (Rp Milyar) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "with a as (\r\n  SELECT \r\n    --CONVERT(VARCHAR(10),TANGGAL_TRANSAKSI,120) trx_date\r\n    trx_date\r\n    ,convert(decimal(18,2),SUM(total_nominal)/1000000000) transaction_volume\r\n  FROM [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()) < 30 \r\n  GROUP BY \r\n    trx_date\r\n    --CONVERT(VARCHAR(10),trx_date,120)\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,trx_date,105),1,2) trx_date\r\n  ,transaction_volume metrics_value\r\nfrom a\r\norder by a.trx_date\r\n"
    },
    {
     "rawSql": "with a as (\r\n  SELECT \r\n    --CONVERT(VARCHAR(10),TANGGAL_TRANSAKSI,120) trx_date\r\n    TANGGAL_TRANSAKSI\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_AMOUNT)/1000000000) transaction_volume\r\n  FROM QRIS.dbo.TRANSAKSI_MPM_OFF_US_SUMMARY_DAILY_SUCCESS_ONLY\r\n  WHERE \r\n    DATEDIFF(DAY,TANGGAL_TRANSAKSI,GETDATE()) < 30 \r\n  GROUP BY \r\n    TANGGAL_TRANSAKSI\r\n    --CONVERT(VARCHAR(10),TANGGAL_TRANSAKSI,120)\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,TANGGAL_TRANSAKSI,105),1,2) trx_date\r\n  ,transaction_volume metrics_value\r\nfrom a\r\norder by a.TANGGAL_TRANSAKSI\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#001852;\"><b><font size=\"5\" color=\"#fffff\">\nTransaction QRIS Monthly\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Summary Frekuensi Transaksi Inflow Outflow QRIS Monthly (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    trx_date\r\n    ,convert(decimal(18,2),sum(jumlah_transaksi)/1000) transaction_frequency    \r\n  from [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, trx_date,getdate()) <= 3 --and rc ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    trx_date\r\n)\r\nselect\r\nyear([trx_date]) as y,\r\nmonth([trx_date]) as m\r\n, SUBSTRING(convert(varchar,[trx_date],7),1,3) as trx_date\r\n ,sum(transaction_frequency) metrics_value\r\nfrom a\r\ngroup by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\norder by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\n"
    },
    {
     "rawSql": "with a as (\r\n  select \r\n    TANGGAL_TRANSAKSI,\r\n    convert(decimal(18,2), sum(TRANSACTION_TOTAL)/1000) as transaction_frequency    \r\n  from QRIS.dbo.TRANSAKSI_MPM_OFF_US_SUMMARY_DAILY_SUCCESS_ONLY\r\n  where \r\n    datediff(MONTH, TANGGAL_TRANSAKSI, getdate()) <= 3\r\n    --and rc ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    TANGGAL_TRANSAKSI\r\n),\r\nb as (\r\n  select\r\n    year(a.TANGGAL_TRANSAKSI) as y,\r\n    month(a.TANGGAL_TRANSAKSI) as m,\r\n    SUBSTRING(convert(varchar, a.TANGGAL_TRANSAKSI, 7), 1, 3) as trx_date,\r\n    sum(a.transaction_frequency) as metrics_value\r\n  from a\r\n  group by year(a.TANGGAL_TRANSAKSI), month(a.TANGGAL_TRANSAKSI), SUBSTRING(convert(varchar, a.TANGGAL_TRANSAKSI, 7), 1, 3)\r\n)\r\nselect y, m, trx_date, metrics_value \r\nfrom b\r\n"
    }
   ]
  },
  {
   "title": "Summary Volume Transaksi QRIS Inflow Outflow Monthly (Rp Milyar) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    trx_date\r\n    ,convert(decimal(18,2),sum(total_nominal)/1000) transaction_volume  \r\n  from [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, trx_date,getdate()) <= 3 --and rc ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    trx_date\r\n)\r\nselect\r\nyear([trx_date]) as y,\r\nmonth([trx_date]) as m\r\n, SUBSTRING(convert(varchar,[trx_date],7),1,3) as trx_date\r\n ,sum(transaction_volume) metrics_value\r\nfrom a\r\ngroup by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\norder by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\n"
    },
    {
     "rawSql": "with a as (\r\n  select \r\n    TANGGAL_TRANSAKSI,\r\n    convert(decimal(18,2), sum(TRANSACTION_AMOUNT)/1000) as transaction_volume  \r\n  from QRIS.dbo.TRANSAKSI_MPM_OFF_US_SUMMARY_DAILY_SUCCESS_ONLY\r\n  where \r\n    datediff(MONTH, TANGGAL_TRANSAKSI, getdate()) <= 3 --and rc ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    TANGGAL_TRANSAKSI\r\n),\r\nb as (\r\n  select\r\n    year(TANGGAL_TRANSAKSI) as y,\r\n    month(TANGGAL_TRANSAKSI) as m,\r\n    SUBSTRING(convert(varchar, TANGGAL_TRANSAKSI, 7), 1, 3) as trx_date,\r\n    sum(transaction_volume) as metrics_value\r\n  from a\r\n  group by year(TANGGAL_TRANSAKSI), month(TANGGAL_TRANSAKSI), SUBSTRING(convert(varchar, TANGGAL_TRANSAKSI, 7), 1, 3)\r\n  -- order by year(TANGGAL_TRANSAKSI), month(TANGGAL_TRANSAKSI), SUBSTRING(convert(varchar, TANGGAL_TRANSAKSI, 7), 1, 3)\r\n)\r\nselect y, m, trx_date, metrics_value \r\nfrom b \r\n"
    }
   ]
  },
  { "title": "Transaction EDC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#1C82AD;\"><b><font size=\"5\" color=\"#fffff\">\nTransaction EDC Realtime\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Frekuensi Selisih Inflow Outflow Transaksi EDC Realtime (Ribu Transaksi) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "Inflow",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outflow-1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "switch :INCNPG* AND rc :\"00\" AND NOT mti:4*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outflow-2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "merch_org: \"000\" and trx_respcode :(00 85) AND trx_posmode : (5 OR 7 OR 97 OR 02 OR 91 OR 90 OR 95) AND trx_currency:360  ",
     "timeField": "trx_datetime"
    }
   ]
  },
  {
   "title": "Volume Selisih Inflow Outflow Transaksi EDC Realtime (Rp Milyar) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "alias": "Inflow ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trxAmount", "id": "1", "type": "sum" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outflow Debit",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trxAmount", "id": "1", "type": "sum" }
     ],
     "query": "switch :INCNPG* AND rc :\"00\" AND NOT mti:4*  ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outflow Kredit",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trx_billamt", "id": "1", "type": "sum" }
     ],
     "query": "merch_org: \"000\" and trx_respcode :(00 85) AND trx_posmode : (5 OR 7 OR 97 OR 02 OR 91 OR 90 OR 95) AND trx_currency:360  ",
     "timeField": "trx_datetime"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#1C82AD;\"><b><font size=\"5\" color=\"#fffff\">\nTransaction EDC Daily\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Frekuensi Selisih Inflow Outflow Transaksi EDC Daily (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "WITH a1 AS (\r\n  SELECT\r\n    Tanggal,\r\n    CONVERT(decimal(18, 2), SUM(TRANSACTION_TOTAL) / 1000) AS transaction_frequency\r\n  FROM\r\n    [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY]\r\n  WHERE\r\n    DATEDIFF(DAY, Tanggal, GETDATE()) < 30 AND RC = '00'\r\n  GROUP BY\r\n    Tanggal\r\n),\r\na2 AS (\r\n  SELECT\r\n    Tanggal,\r\n    CONVERT(decimal(18, 2), SUM(TRANSACTION_TOTAL) / 1000) AS transaction_frequency\r\n  FROM\r\n    KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY]\r\n  WHERE\r\n    DATEDIFF(DAY, Tanggal, GETDATE()) < 30\r\n  GROUP BY\r\n    Tanggal\r\n)\r\nSELECT\r\n  SUBSTRING(CONVERT(VARCHAR, a1.Tanggal, 105), 1, 2) AS trx_date,\r\n  a1.transaction_frequency + a2.transaction_frequency AS total_transaction_frequency\r\nFROM\r\n  a1\r\nJOIN a2 ON a1.Tanggal = a2.Tanggal\r\nORDER BY\r\n  a1.Tanggal;\r\n"
    },
    {
     "rawSql": "WITH \r\na AS (\r\n  select \r\n    convert(DATE,[date]) as trx_date\r\n    ,convert(decimal(18,2),sum(jumlah_transaksi)/1000) transaction_frequency\r\n  from [DataAnalytics].dbo.[incoming_NPG_SummaryDaily]\r\n  where \r\n    datediff(day, [date],getdate()) < 30   \r\n    and rc ='00'\r\n  group by [date]\r\n),\r\nb AS (\r\n  SELECT \r\n    trx_date\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_TOTAL)/1000) transaction_frequency\r\n  FROM KartuKredit.dbo.CC_OFF_US_SUMMARY_DAILY_SUCCESS_ONLY\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()) < 30 \r\n  GROUP BY trx_date\r\n)\r\nSELECT\r\n  SUBSTRING(CONVERT(VARCHAR,b.trx_date,105),1,2) as trx_date,\r\n  a.transaction_frequency + b.transaction_frequency AS total_transaction_frequency\r\nFROM\r\n  b\r\nJOIN a ON b.trx_date = a.trx_date\t\r\norder by b.trx_date"
    }
   ]
  },
  {
   "title": "Volume Selisih Inflow Outflow Transaksi EDC Daily (Rp Milyar) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  SELECT \r\n    Tanggal\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_AMOUNT)/1000000000) transaction_volume     \r\n  FROM [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,Tanggal,GETDATE()) < 30 AND RC = '00'\r\n  GROUP BY \r\n    Tanggal\r\n),\r\nb as (\r\n\tSELECT \r\n    Tanggal\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_AMOUNT)/1000000000) transaction_volume     \r\n  FROM KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,Tanggal,GETDATE()) < 30 \r\n  GROUP BY \r\n    Tanggal\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,a.Tanggal,105),1,2) trx_date\r\n  ,a.transaction_volume + b.transaction_volume as total_transaction_volume\r\nFROM\r\n  a\r\nJOIN b ON a.Tanggal = b.Tanggal\r\nORDER BY\r\n  a.Tanggal;"
    },
    {
     "rawSql": "with  a as (\r\n  select \r\n    [date] as trx_date\r\n    ,convert(decimal(18,2),sum(sales_volume)/1000000000) transaction_volume     \r\n  from [DataAnalytics].dbo.[incoming_NPG_SummaryDaily]\r\n  where \r\n    datediff(day, [date],getdate()) < 30   \r\n    and rc ='00'\r\n  group by \r\n    [date]\r\n), \r\nb as(\r\n\tselect\r\n\ttrx_date\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_AMOUNT)/1000000000) transaction_volume\r\n  FROM KartuKredit.dbo.CC_OFF_US_SUMMARY_DAILY_SUCCESS_ONLY\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()) < 30 \r\n  GROUP BY \r\n    trx_date\r\n)\r\nselect \r\n   SUBSTRING(CONVERT(VARCHAR,a.trx_date,105),1,2) trx_date\r\n  , a.transaction_volume + b.transaction_volume as total_transaction_volume \r\nFROM\r\n  a\r\nJOIN b ON a.trx_date = b.trx_date\r\nORDER BY\r\n  a.trx_date;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#1C82AD;\"><b><font size=\"5\" color=\"#fffff\">\nTransaction EDC Monthly\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Summary Frekuensi Transaksi EDC Monthly (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    trx_date\r\n    ,convert(decimal(18,2),sum(jumlah_transaksi)/1000) transaction_frequency    \r\n  from [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, trx_date,getdate()) <= 6 AND RC = '00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    trx_date\r\n)\r\nselect\r\nyear([trx_date]) as y,\r\nmonth([trx_date]) as m\r\n, SUBSTRING(convert(varchar,[trx_date],7),1,3) as trx_date\r\n ,sum(transaction_frequency) metrics_value\r\nfrom a\r\ngroup by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\norder by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\n"
    },
    {
     "rawSql": "with a as (\r\n  select \r\n    TANGGAL_TRANSAKSI,\r\n    convert(decimal(18,2), sum(TRANSACTION_TOTAL)/1000) as transaction_frequency    \r\n  from QRIS.dbo.TRANSAKSI_MPM_OFF_US_SUMMARY_DAILY_SUCCESS_ONLY\r\n  where \r\n    datediff(MONTH, TANGGAL_TRANSAKSI, getdate()) <= 6\r\n    --and rc ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    TANGGAL_TRANSAKSI\r\n),\r\nb as (\r\n  select\r\n    year(a.TANGGAL_TRANSAKSI) as y,\r\n    month(a.TANGGAL_TRANSAKSI) as m,\r\n    SUBSTRING(convert(varchar, a.TANGGAL_TRANSAKSI, 7), 1, 3) as trx_date,\r\n    sum(a.transaction_frequency) as metrics_value\r\n  from a\r\n  group by year(a.TANGGAL_TRANSAKSI), month(a.TANGGAL_TRANSAKSI), SUBSTRING(convert(varchar, a.TANGGAL_TRANSAKSI, 7), 1, 3)\r\n)\r\nselect y, m, trx_date, metrics_value \r\nfrom b \r\nwhere m in (1, 2, 3, 4);\r\n"
    }
   ]
  },
  {
   "title": "Summary Volume Transaksi EDC Monthly (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    Tanggal\r\n    ,convert(decimal(18,2),sum(TRANSACTION_TOTAL)/1000) as transaction_frequency    \r\n  from [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, Tanggal,getdate()) <= 3 AND RC = '00'\r\n  group by \r\n    Tanggal\r\n),\r\nb as (\r\n  select \r\n    Tanggal\r\n    ,convert(decimal(18,2),sum(TRANSACTION_TOTAL)/1000) as transaction_frequency    \r\n  from KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, Tanggal,getdate()) <= 3\r\n  group by \r\n    Tanggal\r\n)\r\nselect\r\n  year(a.Tanggal) as y,\r\n  month(a.Tanggal) as m,\r\n  SUBSTRING(convert(varchar,a.Tanggal,7),1,3) as trx_date,\r\n  sum(a.transaction_frequency + b.transaction_frequency) as total_transaction_frequency\r\nfrom \r\n  a\r\n  JOIN b ON a.Tanggal = b.Tanggal\r\ngroup by \r\n  year(a.Tanggal), \r\n  month(a.Tanggal), \r\n  SUBSTRING(convert(varchar,a.Tanggal,7),1,3)\r\norder by \r\n  year(a.Tanggal), \r\n  month(a.Tanggal), \r\n  SUBSTRING(convert(varchar,a.Tanggal,7),1,3);"
    },
    {
     "rawSql": "with  a as (\r\n  select \r\n    [date] as trx_date\r\n    ,convert(decimal(18,2),sum(jumlah_transaksi)/1000) transaction_frequency     \r\n  from [DataAnalytics].dbo.[incoming_NPG_SummaryDaily]\r\n  where \r\n    datediff(MONTH, [date],getdate()) <= 3   \r\n    and rc ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    [date]\r\n),\r\nb as (\r\n\t  select \r\n    trx_date\r\n    ,convert(decimal(18,2),sum(TRANSACTION_TOTAL)/1000) transaction_frequency   \r\n  from KartuKredit.dbo.CC_OFF_US_SUMMARY_DAILY_SUCCESS_ONLY\r\n  where \r\n    datediff(MONTH, trx_date,getdate()) <= 3 --and rc ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    trx_date\r\n)\r\nselect\r\nyear(a.trx_date) as y,\r\nmonth(a.trx_date) as m\r\n, SUBSTRING(convert(varchar,a.trx_date,7),1,3) as trx_date\r\n  -- month([date]) monthly\r\n ,sum(a.transaction_frequency + b.transaction_frequency) as total_transaction_frequency \r\nfrom \r\n  a\r\n  JOIN b ON a.trx_date= b.trx_date\r\ngroup by \r\n  year(a.trx_date), \r\n  month(a.trx_date), \r\n  SUBSTRING(convert(varchar,a.trx_date,7),1,3)\r\norder by \r\n  year(a.trx_date), \r\n  month(a.trx_date), \r\n  SUBSTRING(convert(varchar,a.trx_date,7),1,3);"
    }
   ]
  }
 ]
}