{
 "title": "Dashboard Transaksi Nasabah Bank Lain di EDC dan QRIS BRI",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Summary By Number", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 1 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#1C82AD;\"><b><font size=\"5\" color=\"#fffff\">\nSummary H-1\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 1 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#1C82AD;\"><b><font size=\"5\" color=\"#fffff\">\nSummary Today\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Freq Trx QRIS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    trx_date\r\n    ,SUM(jumlah_transaksi) as 'QRIS TRX FREQUENCY'\r\n  FROM QRIS.dbo.incoming_QRIS_EXT_BRI_DAILY\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()-1) = 0 AND resp_code = '00'\r\n  GROUP BY \r\n    trx_date"
    }
   ]
  },
  {
   "title": "Volume Trx QRIS (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    trx_date\r\n    ,convert(decimal(18,2),SUM(total_nominal)/1000000) as 'QRIS SALES VOLUME'\r\n  FROM QRIS.dbo.incoming_QRIS_EXT_BRI_DAILY\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()-1) = 0 AND resp_code = '00'\r\n  GROUP BY \r\n    trx_date"
    }
   ]
  },
  {
   "title": "Freq Trx QRIS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Volume Trx QRIS (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trx_amount_fix", "id": "1", "settings": { "script": "_value/1000000" }, "type": "sum" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Freq Trx Debit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \r\n    Tanggal\r\n    ,sum(TRANSACTION_TOTAL)  as  'Kartu Debit Trx Frequency'   \r\n  from [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY] \r\n  where \r\n    datediff(day, [Tanggal],getdate()-1) = 0 AND RC = '00'\r\n  group by \r\n    Tanggal"
    }
   ]
  },
  {
   "title": "Volume Trx Debit (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \r\n    Tanggal  \r\n    ,convert(decimal(18,2),sum(TRANSACTION_AMOUNT)/1000000) as 'Kartu Debit Sales Volume' \r\n  from [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY] \r\n  where \r\n    datediff(day, [Tanggal],getdate()-1) = 0 AND RC = '00'\r\n  group by \r\n    Tanggal"
    }
   ]
  },
  {
   "title": "Freq Trx Debit & Kredit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Volume Trx Debit & Kredit (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trxAmount", "id": "1", "settings": { "script": "_value/100000000" }, "type": "sum" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Freq Trx Kredit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \r\n    Tanggal\r\n    ,sum(TRANSACTION_TOTAL)  as  'Kartu Kredit Trx Frequency'   \r\n  from KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY] \r\n  where \r\n    datediff(day, [Tanggal],getdate()-1) = 0 AND RC = '00'\r\n  group by \r\n    Tanggal"
    }
   ]
  },
  {
   "title": "Volume Trx Kredit (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \r\n    Tanggal  \r\n    ,convert(decimal(18,2),sum(TRANSACTION_AMOUNT)/1000000) as 'Kartu Kredit Sales Volume' \r\n  from KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY] \r\n  where \r\n    datediff(day, [Tanggal],getdate()-1) = 0 AND RC = '00'\r\n  group by \r\n    Tanggal"
    }
   ]
  },
  {
   "title": "Freq All Trx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI ",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Volume All Trx (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trxAmount", "id": "3", "settings": { "script": "_value/100000000" }, "type": "sum" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trx_amount_fix", "id": "3", "settings": { "script": "_value/1000000" }, "type": "sum" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Freq All Trx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \r\n    Tanggal\r\n    ,sum(TRANSACTION_TOTAL)  as  'Kartu Kredit Trx Frequency'   \r\n  from KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY] \r\n  where \r\n    datediff(day, [Tanggal],getdate()-1) = 0 AND RC = '00'\r\n  group by \r\n    Tanggal"
    },
    {
     "rawSql": "select \r\n    Tanggal\r\n    ,sum(TRANSACTION_TOTAL)  as  'Kartu Debit Trx Frequency'   \r\n  from [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY] \r\n  where \r\n    datediff(day, [Tanggal],getdate()-1) = 0 AND RC = '00'\r\n  group by \r\n    Tanggal"
    },
    {
     "rawSql": "SELECT \r\n    trx_date as Tanggal\r\n    ,SUM(jumlah_transaksi) as 'QRIS TRX FREQUENCY'\r\n  FROM QRIS.dbo.incoming_QRIS_EXT_BRI_DAILY\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()-1) = 0 AND resp_code = '00'\r\n  GROUP BY \r\n    trx_date"
    }
   ]
  },
  {
   "title": "Volume All Trx (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \r\n    Tanggal  \r\n    ,convert(decimal(18,2),sum(TRANSACTION_AMOUNT)/1000000) as 'Kartu Kredit Sales Volume' \r\n  from KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY] \r\n  where \r\n    datediff(day, [Tanggal],getdate()-1) = 0 AND RC = '00'\r\n  group by \r\n    Tanggal"
    },
    {
     "rawSql": "select \r\n    Tanggal  \r\n    ,convert(decimal(18,2),sum(TRANSACTION_AMOUNT)/1000000) as 'Kartu Debit Sales Volume' \r\n  from [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY] \r\n  where \r\n    datediff(day, [Tanggal],getdate()-1) = 0 AND RC = '00'\r\n  group by \r\n    Tanggal"
    },
    {
     "rawSql": "SELECT \r\n    trx_date as Tanggal\r\n    ,convert(decimal(18,2),SUM(total_nominal)/1000000) as 'QRIS SALES VOLUME'\r\n  FROM QRIS.dbo.incoming_QRIS_EXT_BRI_DAILY\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()-1) = 0 AND resp_code = '00'\r\n  GROUP BY \r\n    trx_date"
    }
   ]
  },
  { "title": "Summary Monthly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#1C82AD;\"><b><font size=\"5\" color=\"#ffffff\">\nData Transaksi Monthly\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Summary Frekuensi Transaksi QRIS Monthly (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    trx_date\r\n    ,convert(decimal(18,2),sum(jumlah_transaksi)/1000) transaction_frequency    \r\n  from [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, trx_date,getdate()) <= 6 and resp_code ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    trx_date\r\n)\r\nselect\r\nyear([trx_date]) as y,\r\nmonth([trx_date]) as m\r\n, SUBSTRING(convert(varchar,[trx_date],7),1,3) as trx_date\r\n ,sum(transaction_frequency) metrics_value\r\nfrom a\r\ngroup by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\norder by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\n"
    }
   ]
  },
  {
   "title": "Summary Frekuensi Transaksi Kartu Debit Monthly (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    Tanggal\r\n    ,convert(decimal(18,2),sum(TRANSACTION_TOTAL)/1000) transaction_frequency    \r\n  from [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, Tanggal,getdate()) <= 6 and RC ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    Tanggal\r\n)\r\nselect\r\nyear([Tanggal]) as y,\r\nmonth([Tanggal]) as m\r\n, SUBSTRING(convert(varchar,[Tanggal],7),1,3) as trx_date\r\n ,sum(transaction_frequency) metrics_value\r\nfrom a\r\ngroup by year([Tanggal]), month([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\norder by year([Tanggal]), month([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\n"
    },
    {
     "rawSql": "with  a as (\r\n  select \r\n    Tanggal\r\n    ,convert(decimal(18,2),sum(TRANSACTION_TOTAL)/1000) transaction_frequency    \r\n  from [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, Tanggal,getdate()) <= 6 \r\n    and DATEDIFF(DAY,Tanggal,GETDATE()) < 30\r\n    --and rc ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    Tanggal\r\n)\r\nselect\r\nyear([Tanggal]) as y,\r\nmonth([Tanggal]) as m,\r\nday([Tanggal]) as d\r\n, SUBSTRING(convert(varchar,[Tanggal],7),1,3) as trx_date\r\n ,sum(transaction_frequency) metrics_value\r\nfrom a\r\ngroup by year([Tanggal]), month([Tanggal]), day([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\norder by year([Tanggal]), month([Tanggal]), day([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)"
    }
   ]
  },
  {
   "title": "Summary Frekuensi Transaksi Kartu Kredit Monthly (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    Tanggal\r\n    ,convert(decimal(18,2),sum(TRANSACTION_TOTAL)/1000) transaction_frequency    \r\n  from KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, Tanggal,getdate()) <= 6 and RC ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    Tanggal\r\n)\r\nselect\r\nyear([Tanggal]) as y,\r\nmonth([Tanggal]) as m\r\n, SUBSTRING(convert(varchar,[Tanggal],7),1,3) as trx_date\r\n ,sum(transaction_frequency) metrics_value\r\nfrom a\r\ngroup by year([Tanggal]), month([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\norder by year([Tanggal]), month([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\n"
    }
   ]
  },
  {
   "title": "Summary Sales Volume QRIS Monthly (Rp Milyar)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    trx_date\r\n    ,convert(decimal(18,2),sum(total_nominal)/1000000000) transaction_volume  \r\n  from [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, trx_date,getdate()) <= 6 and resp_code ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    trx_date\r\n)\r\nselect\r\nyear([trx_date]) as y,\r\nmonth([trx_date]) as m\r\n, SUBSTRING(convert(varchar,[trx_date],7),1,3) as trx_date\r\n ,sum(transaction_volume) metrics_value\r\nfrom a\r\ngroup by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\norder by year([trx_date]), month([trx_date]), SUBSTRING(convert(varchar,[trx_date],7),1,3)\r\n"
    }
   ]
  },
  {
   "title": "Summary Sales Volume Kartu Debit Monthly (Rp Milyar)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    Tanggal\r\n    ,convert(decimal(18,2),sum(TRANSACTION_AMOUNT)/1000000000) transaction_volume    \r\n  from [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, Tanggal,getdate()) <= 6 and RC ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    Tanggal\r\n)\r\nselect\r\nyear([Tanggal]) as y,\r\nmonth([Tanggal]) as m\r\n, SUBSTRING(convert(varchar,[Tanggal],7),1,3) as trx_date\r\n ,sum(transaction_volume) metrics_value\r\nfrom a\r\ngroup by year([Tanggal]), month([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\norder by year([Tanggal]), month([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\n"
    }
   ]
  },
  {
   "title": "Summary Sales Volume Kartu Kredit Monthly (Rp Milyar)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  select \r\n    Tanggal\r\n    ,convert(decimal(18,2),sum(TRANSACTION_AMOUNT)/1000000000) transaction_volume    \r\n  from KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY]\r\n  where \r\n    datediff(MONTH, Tanggal,getdate()) <= 6 and RC ='00'\r\n    --and convert(varchar(7), [date],120) >= '2023-06'\r\n  group by \r\n    Tanggal\r\n)\r\nselect\r\nyear([Tanggal]) as y,\r\nmonth([Tanggal]) as m\r\n, SUBSTRING(convert(varchar,[Tanggal],7),1,3) as trx_date\r\n ,sum(transaction_volume) metrics_value\r\nfrom a\r\ngroup by year([Tanggal]), month([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\norder by year([Tanggal]), month([Tanggal]), SUBSTRING(convert(varchar,[Tanggal],7),1,3)\r\n"
    }
   ]
  },
  { "title": "Summary Daily", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#1C82AD;\"><b><font size=\"5\" color=\"#ffffff\">\nData Transaksi Daily\n</font></b></p>\n</CENTER>"
   }
  },
  {
   "title": "Summary Frekuensi Transaksi QRIS Daily (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  SELECT \r\n    --CONVERT(VARCHAR(10),trx_date,120) trx_date\r\n    trx_date\r\n    ,convert(decimal(18,2),SUM(jumlah_transaksi)/1000) transaction_frequency\r\n  FROM [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()) < 30 and resp_code = '00'\r\n  GROUP BY \r\n    trx_date\r\n    --CONVERT(VARCHAR(10),trx_date,120)\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,trx_date,105),1,2) trx_date\r\n  ,transaction_frequency metrics_value\r\nfrom a\r\norder by a.trx_date"
    }
   ]
  },
  {
   "title": "Summary Frekuensi Transaksi Kartu Debit Daily (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  SELECT \r\n    Tanggal\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_TOTAL)/1000) transaction_frequency\r\n  FROM [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,Tanggal,GETDATE()) < 30 and RC ='00'\r\n  GROUP BY \r\n    Tanggal\r\n)\r\nselect \r\n   SUBSTRING(CONVERT(VARCHAR,Tanggal,105),1,2) trx_date\r\n  ,transaction_frequency metrics_value\r\nfrom a\r\norder by a.Tanggal"
    }
   ]
  },
  {
   "title": "Summary Frekuensi Transaksi Kartu Kredit Daily (Ribu Transaksi) ",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  SELECT \r\n    Tanggal\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_TOTAL)/1000) transaction_frequency\r\n  FROM KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,Tanggal,GETDATE()) < 30 and RC ='00'\r\n  GROUP BY \r\n    Tanggal\r\n)\r\nselect \r\n   SUBSTRING(CONVERT(VARCHAR,Tanggal,105),1,2) trx_date\r\n  ,transaction_frequency metrics_value\r\nfrom a\r\norder by a.Tanggal"
    }
   ]
  },
  {
   "title": "Summary Sales Volume QRIS Daily (Rp Milyar)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "with a as (\r\n  SELECT \r\n    --CONVERT(VARCHAR(10),TANGGAL_TRANSAKSI,120) trx_date\r\n    trx_date\r\n    ,convert(decimal(18,2),SUM(total_nominal)/1000000000) transaction_volume\r\n  FROM [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,trx_date,GETDATE()) < 30 and resp_code = '00'\r\n  GROUP BY \r\n    trx_date\r\n    --CONVERT(VARCHAR(10),trx_date,120)\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,trx_date,105),1,2) trx_date\r\n  ,transaction_volume metrics_value\r\nfrom a\r\norder by a.trx_date\r\n"
    }
   ]
  },
  {
   "title": "Summary Sales Volume Kartu Debit Daily (Rp Milyar)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  SELECT \r\n    Tanggal\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_AMOUNT)/1000000000) transaction_volume     \r\n  FROM [DataAnalytics].dbo.[incoming_NPG_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,Tanggal,GETDATE()) < 30 and RC ='00'\r\n  GROUP BY \r\n    Tanggal\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,Tanggal,105),1,2) trx_date\r\n  ,transaction_volume metrics_value\r\nfrom a\r\norder by a.Tanggal"
    }
   ]
  },
  {
   "title": "Summary Sales Volume Kartu Kredit Daily (Rp Milyar)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "rawSql": "with  a as (\r\n  SELECT \r\n    Tanggal\r\n    ,convert(decimal(18,2),SUM(TRANSACTION_AMOUNT)/1000000000) transaction_volume     \r\n  FROM KartuKredit.dbo.[incoming_CC_EXT_BRI_DAILY]\r\n  WHERE \r\n    DATEDIFF(DAY,Tanggal,GETDATE()) < 30 and RC ='00'\r\n  GROUP BY \r\n    Tanggal\r\n)\r\nselect \r\n  SUBSTRING(CONVERT(VARCHAR,Tanggal,105),1,2) trx_date\r\n  ,transaction_volume metrics_value\r\nfrom a\r\norder by a.Tanggal"
    }
   ]
  },
  {
   "title": "Transaksi QRIS Realtime Nasabah Bank Lain di BRI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 }
  },
  {
   "title": "Freq Trx QRIS  Nasabah Bank Lain di BRI (per 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 66 },
   "targets": [
    {
     "alias": "Freq Trx QRIS  Nasabah Bank Lain di BRI",
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Volume Trx QRIS  Nasabah Bank Lain di BRI  (per 5m) (Rp Juta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 66 },
   "targets": [
    {
     "alias": "Volume Trx QRIS  Nasabah Bank Lain di BRI ",
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trx_amount", "id": "1", "settings": { "script": "_value/100000000" }, "type": "sum" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Transaksi Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Volume Transaksi Today (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "trx_datetime", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trx_amount_fix", "id": "1", "settings": { "script": "_value/1000000" }, "type": "sum" }
     ],
     "query": "NOT cpan_code: \"93600002\" AND resp_code: \"00\" AND trx_type: \"2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Merchant",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "iss_name.keyword",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "10", "size": "100" },
       "type": "terms"
      },
      {
       "field": "cpan_code.keyword",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "10", "size": "100" },
       "type": "terms"
      },
      {
       "field": "acquire_institution_id.keyword",
       "id": "16",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "10", "size": "100" },
       "type": "terms"
      },
      {
       "field": "iss_mid.keyword",
       "id": "17",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "10", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      {
       "field": "trx_amount_fix",
       "hide": false,
       "id": "10",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "NOT cpan_code: 93600002 AND resp_code : 00 AND trx_type : 2",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Issuer Success Only",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cpan_code.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "6", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "trx_amount_fix", "id": "6", "type": "sum" }
     ],
     "query": "NOT cpan_code: 93600002 AND resp_code : 00 AND trx_type : 2",
     "timeField": "@timestamp"
    },
    {
     "rawSql": "select issuer_code as 'cpan_code.keyword',issuer_name  FROM QRIS.dbo.tbl_issuer_id"
    }
   ]
  },
  {
   "title": "Top Issuer H-1 With Percentage",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "rawSql": "WITH a AS (\r\n  SELECT\r\n    SUBSTRING(cpan, 0, 9) AS issuer_code,\r\n    COUNT(resp_code) AS total_trx,\r\n    SUM(total_nominal) AS total_volume,\r\n    SUM(CASE WHEN resp_code = '00' THEN 1 ELSE 0 END) AS total_success,\r\n    SUM(CASE WHEN resp_code != '00' THEN 1 ELSE 0 END) AS total_failure,\r\n    SUM(CASE WHEN resp_code = '00' THEN total_nominal ELSE 0 END) AS success_volume,\r\n    SUM(CASE WHEN resp_code != '00' THEN total_nominal ELSE 0 END) AS failure_volume\r\n  FROM\r\n    [QRIS].[dbo].[incoming_QRIS_EXT_BRI_DAILY]\r\n  WHERE\r\n    DATEDIFF(DAY,trx_date,GETDATE()-1) = 0 \r\n  GROUP BY\r\n    SUBSTRING(cpan, 0, 9)\r\n), \r\nb AS (\r\n  SELECT\r\n    issuer_code,\r\n    issuer_name \r\n  FROM\r\n    QRIS.dbo.tbl_issuer_id\r\n)\r\nSELECT\r\n  a.issuer_code,\r\n  total_trx,\r\n  total_success,\r\n  total_failure,\r\n  CONVERT(DECIMAL(4, 1), (total_success * 100.0) / total_trx) AS percent_success,\r\n  CONVERT(DECIMAL(4, 1), (total_failure * 100.0) / total_trx) AS percent_failure,\r\n  CONVERT(decimal(18,2),SUM(a.success_volume) / 1000000) AS success_volume,\r\n  CONVERT(decimal(18,2),SUM(a.failure_volume) / 1000000) AS failure_volume,\r\n  CONVERT(decimal(18,2),SUM(a.total_volume)/ 1000000 ) AS total_volume,\r\n  b.issuer_name\r\nFROM\r\n  a\r\nJOIN \r\n  b ON a.issuer_code = b.issuer_code\r\nGROUP BY\r\n  a.issuer_code,\r\n  total_trx,\r\n  total_success,\r\n  total_failure,\r\n  b.issuer_name,\r\n  a.total_volume\r\nORDER BY \r\n  total_trx DESC;"
    }
   ]
  },
  {
   "title": "Transaksi Nasabah Bank Lain di EDC BRI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }
  },
  {
   "title": "Freq Trx EDC Nasabah Bank Lain di BRI (per 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 109 },
   "targets": [
    {
     "alias": "Freq Trx Kartu Debit & Kredit Bank Lain di Merchant BRI",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Volume Trx EDC Nasabah Bank Lain di BRI (per 5m) (Rp Juta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 109 },
   "targets": [
    {
     "alias": "Volume Trx Kartu Debit & Kredit Bank Lain di Merchant BRI",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trxAmount", "id": "1", "settings": { "script": "_value/100000000" }, "type": "sum" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Transaksi Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 109 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Volume Transaksi Today (Rp Juta)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trxAmount", "id": "1", "settings": { "script": "_value/100000000" }, "type": "sum" }
     ],
     "query": "switch :\"PSW X\" AND NOT jenisTrx :BRI AND rc: \"00\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Merchant",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "merchantName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "location.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "switch.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "midOrMPAN.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "bin_kartu.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "trxAmount", "id": "4", "settings": { "script": "_value/100" }, "type": "sum" }
     ],
     "query": "switch :\"PSW X\" AND rc:\"00\" AND NOT jenisTrx :BRI",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}